### ISSUE TITLE
Go-Live Checklist

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#90]
[Reference](https://www.hlx.live/docs/go-live-checklist)

- [ ] Content and Design QA
- [ ] Performance Valadation
  - [ ] See #1 
- [ ] Analytics Validation
- [ ] Legacy Redirects
- [ ] Sitemap and Robots
- [ ] Favicon
- [ ] CDN Configuration
  - [ ] See #29 
- [ ] Push Invalidation Setup
- [ ] Update Production Host
